---

- name: APT | Install Galera
  ansible.builtin.apt:
    name: "{{ mariadb_galera_package_name }}"

- name: TEMPLATE | Deploy Galera configuration
  ansible.builtin.template:
    src: etc/mysql/mariadb.conf.d/60-galera.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf
    mode: 0644
    owner: root
    group: root
  notify: Restart mariadb

- name: INCLUDE | Bootstrap first node
  ansible.builtin.import_tasks: 'bootstrap.yml'
  when: inventory_hostname == mariadb_galera_primary_node

- name: META | Flush handlers
  ansible.builtin.meta: flush_handlers
