---

- name: COMMAND | GET debian.cnf from primary node
  command: cat /etc/mysql/debian.cnf
  register: debiancnf
  delegate_to: '{{ mysql_galera_primary_node }}'
  changed_when: false

- name: COMMAND | Get current debian.cnf
  command: cat /etc/mysql/debian.cnf
  register: ondc
  changed_when: false

- block:

  - name: SERVICE | Stop MariaDB
    service: name=mysql state=stopped

  - name: COPY | Paste primary node's debian.cnf
    copy: >
      content={{ debiancnf.stdout }}
      dest=/etc/mysql/debian.cnf
      mode=0600
      owner=root
      group=root
    register: paste

  - name: SERVICE | Start MariaDB
    service: name=mysql state=started

  when: debiancnf.stdout != ondc.stdout
