---

- name: MYSQL_USER | Remove all anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MYSQL_DB | Remove the test database
  mysql_db:
    name: test
    state: absent
