---

mariadb_replication_master: false
mariadb_replication_slave: true
mariadb_replication_user: 'replication'
mariadb_replication_password: '1a2b3c'
mariadb_slave_ignore_db: ['norepl']
mariadb_slave_import_from: "{{ groups['master'][0] }}"
mariadb_replication_host: "{{ groups['master'][0] }}"

# vim: set ft=yaml :
