---

- name: MYSQL_REPLICATION | Stop slave
  mysql_replication:
    mode: stopslave

- name: MYSQL_REPLICATION | Configure master host
  mysql_replication:
    mode: changemaster
    master_host: "{{ mariadb_replication_host }}"
    master_port: "{{ mariadb_replication_port }}"
    master_user: "{{ mariadb_replication_user }}"
    master_password: "{{ mariadb_replication_password }}"

# -- Wait this PR in Ansible released version (https://github.com/ansible/ansible/pull/62648)
# name: MYSQL_REPLICATION | Setup replication with GTID
# mysql_replication:
#   master_use_gtid: current_pos

- name: COMMAND | Configure GTID
  command: mariadb -e "CHANGE MASTER TO master_use_gtid=current_pos";
  changed_when: true

- name: MYSQL_REPLICATION | Start slave
  mysql_replication:
    mode: startslave
