---

- name: TEMPLATE | Deploy master configuration
  template:
    src: etc/mysql/mariadb.conf.d/40-master.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/40-master.cnf
    mode: 0644
    owner: root
    group: root
  notify: restart mariadb
