---

name: Deploy on Ansible Galaxy

'on':
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Import role to Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
          --branch fix_galaxy
